<?php

namespace AppBundle\Repository;

/**
 * EventTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventTagRepository extends \Doctrine\ORM\EntityRepository
{
}
