<?php

namespace AppBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * EventTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventTagRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTagsSearchQuery(array $criteria = [])
    {
        $queryBuilder = $this->createQueryBuilder('tag');

        $this
            ->filterByTitle($queryBuilder, $criteria)
            ->orderBy('tag.title', 'ASC');

        return $queryBuilder->getQuery();
    }

    private function filterByTitle(QueryBuilder $queryBuilder, array $criteria)
    {
        if (isset($criteria['title']))
        {
            $queryBuilder
                ->andWhere('tag.title LIKE :title')
                ->setParameter('title', $criteria['title'] . '%');
        }

        return $queryBuilder;
    }
}
