<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * EventUploadedPictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventPictureRepository extends \Doctrine\ORM\EntityRepository
{
    private function getUserUnlinkedEventPicturesQuery(User $user)
    {
        return $this->createQueryBuilder('picture')
            ->where('picture.user = :user')
            ->andWhere('picture.event IS NULL')
            ->setParameter('user', $user)
            ->getQuery();
    }

    public function getUserAllUnlinkedEventPictures(User $user)
    {
        return $this->getUserUnlinkedEventPicturesQuery($user)->getResult();
    }

}
