<?php

namespace AppBundle\Repository;

/**
 * VideoLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoLinkRepository extends \Doctrine\ORM\EntityRepository
{
}
