imports:
    - { resource: config_test.yml }
    - { resource: csa_guzzle.yml }

framework:
    profiler:
        only_exceptions: false
        collect: true

web_profiler:
    toolbar: true

csa_guzzle:
    logger: true
    clients:
        local_test_api:
            config:
                base_uri: "http://127.0.0.1:8001/app_acceptance.php/api/"

parameters:
    database_name: "event_stream_test"