login:
    type: rest
    resource: AppBundle\Controller\RestLoginController

registration:
    type: rest
    resource: AppBundle\Controller\RestRegistrationController

event:
    type: annotation
    resource: AppBundle\Controller\EventController

tag:
    type: annotation
    resource: AppBundle\Controller\EventTagController