services:
  event.manager:
    class: AppBundle\Service\EventManager
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@form.factory'
      - '@form_error_extractor.helper'
      - '@tag.manager'
    public: true

  tag.manager:
    class: AppBundle\Service\EventTagManager
    arguments: ['@doctrine.orm.entity_manager']
    public: true

  video_link.manager:
    class: AppBundle\Service\Video\VideoLinkManager
    arguments: ['@doctrine.orm.entity_manager', '@video_link.provider.factory']
    public: true

  event_comment.manager:
    class: AppBundle\Service\EventCommentManager
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@form.factory'
      - '@form_error_extractor.helper'
    public: true

  event.form:
    class: AppBundle\Form\Type\EventType
    tags: [form.type]
    public: true

  form_error_extractor.helper:
    class: AppBundle\Service\FormErrorExtractor
    public: true

  event_picture.serialize.listener:
    class: AppBundle\Event\Subscriber\EventPictureSerializeSubscriber
    arguments: ['@vich_uploader.templating.helper.uploader_helper', '@liip_imagine.cache.manager']
    public: true
    tags: [jms_serializer.event_subscriber]

  event.serialize.listener:
    class: AppBundle\Event\Subscriber\EventSerializeSubscriber
    arguments: ['@security.token_storage']
    public: true
    tags: [jms_serializer.event_subscriber]

  event_comment.serialize.listener:
    class: AppBundle\Event\Subscriber\EventCommentSerializeSubscriber
    arguments: ['@security.token_storage']
    public: true
    tags: [jms_serializer.event_subscriber]

  video_link.provider.factory:
    class: AppBundle\Service\Video\VideoProviderFactory

  event_picture.data_transformer:
    class: AppBundle\Form\DataTransformer\EventPictureTransformer
    arguments: ['@doctrine.orm.entity_manager']