services:
  event.manager:
    class: AppBundle\Service\EventManager
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@form.factory'
      - '@form_error_extractor.helper'
      - '@tag.manager'
    public: true

  tag.manager:
    class: AppBundle\Service\EventTagManager
    arguments: ['@doctrine.orm.entity_manager']
    public: true

  event.form:
    class: AppBundle\Form\Type\EventType
    tags: [form.type]
    public: true

  form_error_extractor.helper:
    class: AppBundle\Service\FormErrorExtractor
    public: true

  event_picture.serialize.listener:
    class: AppBundle\EventListener\EventPictureSerializeSubscriber
    arguments: ['@vich_uploader.templating.helper.uploader_helper', '@liip_imagine.cache.manager']
    public: true
    tags: [jms_serializer.event_subscriber]


  event_picture.data_transformer:
    class: AppBundle\Form\DataTransformer\EventPictureTransformer
    arguments: ['@doctrine.orm.entity_manager']